// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/src/main/java/google/protobuf/xavier.proto

package org.xavier.domain.protobufObj;

public final class ProtoBuf {
  private ProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:google.protobuf.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string uName = 1;</code>
     */
    String getUName();
    /**
     * <code>string uName = 1;</code>
     */
    com.google.protobuf.ByteString
        getUNameBytes();

    /**
     * <code>repeated .google.protobuf.Article articles = 2;</code>
     */
    java.util.List<Article>
        getArticlesList();
    /**
     * <code>repeated .google.protobuf.Article articles = 2;</code>
     */
    ProtoBuf.Article getArticles(int index);
    /**
     * <code>repeated .google.protobuf.Article articles = 2;</code>
     */
    int getArticlesCount();
    /**
     * <code>repeated .google.protobuf.Article articles = 2;</code>
     */
    java.util.List<? extends ArticleOrBuilder>
        getArticlesOrBuilderList();
    /**
     * <code>repeated .google.protobuf.Article articles = 2;</code>
     */
    ProtoBuf.ArticleOrBuilder getArticlesOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code google.protobuf.User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:google.protobuf.User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      uName_ = "";
      articles_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              uName_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                articles_ = new java.util.ArrayList<Article>();
                mutable_bitField0_ |= 0x00000002;
              }
              articles_.add(
                  input.readMessage(ProtoBuf.Article.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          articles_ = java.util.Collections.unmodifiableList(articles_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoBuf.internal_static_google_protobuf_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoBuf.internal_static_google_protobuf_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoBuf.User.class, ProtoBuf.User.Builder.class);
    }

    private int bitField0_;
    public static final int UNAME_FIELD_NUMBER = 1;
    private volatile Object uName_;
    /**
     * <code>string uName = 1;</code>
     */
    public String getUName() {
      Object ref = uName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        uName_ = s;
        return s;
      }
    }
    /**
     * <code>string uName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUNameBytes() {
      Object ref = uName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        uName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARTICLES_FIELD_NUMBER = 2;
    private java.util.List<Article> articles_;
    /**
     * <code>repeated .google.protobuf.Article articles = 2;</code>
     */
    public java.util.List<Article> getArticlesList() {
      return articles_;
    }
    /**
     * <code>repeated .google.protobuf.Article articles = 2;</code>
     */
    public java.util.List<? extends ArticleOrBuilder>
        getArticlesOrBuilderList() {
      return articles_;
    }
    /**
     * <code>repeated .google.protobuf.Article articles = 2;</code>
     */
    public int getArticlesCount() {
      return articles_.size();
    }
    /**
     * <code>repeated .google.protobuf.Article articles = 2;</code>
     */
    public ProtoBuf.Article getArticles(int index) {
      return articles_.get(index);
    }
    /**
     * <code>repeated .google.protobuf.Article articles = 2;</code>
     */
    public ProtoBuf.ArticleOrBuilder getArticlesOrBuilder(
        int index) {
      return articles_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uName_);
      }
      for (int i = 0; i < articles_.size(); i++) {
        output.writeMessage(2, articles_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uName_);
      }
      for (int i = 0; i < articles_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, articles_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoBuf.User)) {
        return super.equals(obj);
      }
      ProtoBuf.User other = (ProtoBuf.User) obj;

      boolean result = true;
      result = result && getUName()
          .equals(other.getUName());
      result = result && getArticlesList()
          .equals(other.getArticlesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUName().hashCode();
      if (getArticlesCount() > 0) {
        hash = (37 * hash) + ARTICLES_FIELD_NUMBER;
        hash = (53 * hash) + getArticlesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoBuf.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoBuf.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoBuf.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoBuf.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoBuf.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoBuf.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoBuf.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoBuf.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoBuf.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtoBuf.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoBuf.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoBuf.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoBuf.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code google.protobuf.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:google.protobuf.User)
        ProtoBuf.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoBuf.internal_static_google_protobuf_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoBuf.internal_static_google_protobuf_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoBuf.User.class, ProtoBuf.User.Builder.class);
      }

      // Construct using org.xavier.domain.protobufObj.ProtoBuf.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getArticlesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        uName_ = "";

        if (articlesBuilder_ == null) {
          articles_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          articlesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoBuf.internal_static_google_protobuf_User_descriptor;
      }

      public ProtoBuf.User getDefaultInstanceForType() {
        return ProtoBuf.User.getDefaultInstance();
      }

      public ProtoBuf.User build() {
        ProtoBuf.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoBuf.User buildPartial() {
        ProtoBuf.User result = new ProtoBuf.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.uName_ = uName_;
        if (articlesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            articles_ = java.util.Collections.unmodifiableList(articles_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.articles_ = articles_;
        } else {
          result.articles_ = articlesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoBuf.User) {
          return mergeFrom((ProtoBuf.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoBuf.User other) {
        if (other == ProtoBuf.User.getDefaultInstance()) return this;
        if (!other.getUName().isEmpty()) {
          uName_ = other.uName_;
          onChanged();
        }
        if (articlesBuilder_ == null) {
          if (!other.articles_.isEmpty()) {
            if (articles_.isEmpty()) {
              articles_ = other.articles_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureArticlesIsMutable();
              articles_.addAll(other.articles_);
            }
            onChanged();
          }
        } else {
          if (!other.articles_.isEmpty()) {
            if (articlesBuilder_.isEmpty()) {
              articlesBuilder_.dispose();
              articlesBuilder_ = null;
              articles_ = other.articles_;
              bitField0_ = (bitField0_ & ~0x00000002);
              articlesBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getArticlesFieldBuilder() : null;
            } else {
              articlesBuilder_.addAllMessages(other.articles_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoBuf.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoBuf.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object uName_ = "";
      /**
       * <code>string uName = 1;</code>
       */
      public String getUName() {
        Object ref = uName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          uName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string uName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUNameBytes() {
        Object ref = uName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          uName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uName = 1;</code>
       */
      public Builder setUName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        uName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string uName = 1;</code>
       */
      public Builder clearUName() {

        uName_ = getDefaultInstance().getUName();
        onChanged();
        return this;
      }
      /**
       * <code>string uName = 1;</code>
       */
      public Builder setUNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        uName_ = value;
        onChanged();
        return this;
      }

      private java.util.List<Article> articles_ =
        java.util.Collections.emptyList();
      private void ensureArticlesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          articles_ = new java.util.ArrayList<Article>(articles_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProtoBuf.Article, ProtoBuf.Article.Builder, ProtoBuf.ArticleOrBuilder> articlesBuilder_;

      /**
       * <code>repeated .google.protobuf.Article articles = 2;</code>
       */
      public java.util.List<Article> getArticlesList() {
        if (articlesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(articles_);
        } else {
          return articlesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .google.protobuf.Article articles = 2;</code>
       */
      public int getArticlesCount() {
        if (articlesBuilder_ == null) {
          return articles_.size();
        } else {
          return articlesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .google.protobuf.Article articles = 2;</code>
       */
      public ProtoBuf.Article getArticles(int index) {
        if (articlesBuilder_ == null) {
          return articles_.get(index);
        } else {
          return articlesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .google.protobuf.Article articles = 2;</code>
       */
      public Builder setArticles(
          int index, ProtoBuf.Article value) {
        if (articlesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArticlesIsMutable();
          articles_.set(index, value);
          onChanged();
        } else {
          articlesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Article articles = 2;</code>
       */
      public Builder setArticles(
          int index, ProtoBuf.Article.Builder builderForValue) {
        if (articlesBuilder_ == null) {
          ensureArticlesIsMutable();
          articles_.set(index, builderForValue.build());
          onChanged();
        } else {
          articlesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Article articles = 2;</code>
       */
      public Builder addArticles(ProtoBuf.Article value) {
        if (articlesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArticlesIsMutable();
          articles_.add(value);
          onChanged();
        } else {
          articlesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Article articles = 2;</code>
       */
      public Builder addArticles(
          int index, ProtoBuf.Article value) {
        if (articlesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureArticlesIsMutable();
          articles_.add(index, value);
          onChanged();
        } else {
          articlesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Article articles = 2;</code>
       */
      public Builder addArticles(
          ProtoBuf.Article.Builder builderForValue) {
        if (articlesBuilder_ == null) {
          ensureArticlesIsMutable();
          articles_.add(builderForValue.build());
          onChanged();
        } else {
          articlesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Article articles = 2;</code>
       */
      public Builder addArticles(
          int index, ProtoBuf.Article.Builder builderForValue) {
        if (articlesBuilder_ == null) {
          ensureArticlesIsMutable();
          articles_.add(index, builderForValue.build());
          onChanged();
        } else {
          articlesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Article articles = 2;</code>
       */
      public Builder addAllArticles(
          Iterable<? extends Article> values) {
        if (articlesBuilder_ == null) {
          ensureArticlesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, articles_);
          onChanged();
        } else {
          articlesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Article articles = 2;</code>
       */
      public Builder clearArticles() {
        if (articlesBuilder_ == null) {
          articles_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          articlesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Article articles = 2;</code>
       */
      public Builder removeArticles(int index) {
        if (articlesBuilder_ == null) {
          ensureArticlesIsMutable();
          articles_.remove(index);
          onChanged();
        } else {
          articlesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .google.protobuf.Article articles = 2;</code>
       */
      public ProtoBuf.Article.Builder getArticlesBuilder(
          int index) {
        return getArticlesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .google.protobuf.Article articles = 2;</code>
       */
      public ProtoBuf.ArticleOrBuilder getArticlesOrBuilder(
          int index) {
        if (articlesBuilder_ == null) {
          return articles_.get(index);  } else {
          return articlesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .google.protobuf.Article articles = 2;</code>
       */
      public java.util.List<? extends ArticleOrBuilder>
           getArticlesOrBuilderList() {
        if (articlesBuilder_ != null) {
          return articlesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(articles_);
        }
      }
      /**
       * <code>repeated .google.protobuf.Article articles = 2;</code>
       */
      public ProtoBuf.Article.Builder addArticlesBuilder() {
        return getArticlesFieldBuilder().addBuilder(
            ProtoBuf.Article.getDefaultInstance());
      }
      /**
       * <code>repeated .google.protobuf.Article articles = 2;</code>
       */
      public ProtoBuf.Article.Builder addArticlesBuilder(
          int index) {
        return getArticlesFieldBuilder().addBuilder(
            index, ProtoBuf.Article.getDefaultInstance());
      }
      /**
       * <code>repeated .google.protobuf.Article articles = 2;</code>
       */
      public java.util.List<Article.Builder>
           getArticlesBuilderList() {
        return getArticlesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProtoBuf.Article, ProtoBuf.Article.Builder, ProtoBuf.ArticleOrBuilder>
          getArticlesFieldBuilder() {
        if (articlesBuilder_ == null) {
          articlesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ProtoBuf.Article, ProtoBuf.Article.Builder, ProtoBuf.ArticleOrBuilder>(
                  articles_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          articles_ = null;
        }
        return articlesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:google.protobuf.User)
    }

    // @@protoc_insertion_point(class_scope:google.protobuf.User)
    private static final ProtoBuf.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoBuf.User();
    }

    public static ProtoBuf.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    public ProtoBuf.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ArticleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:google.protobuf.Article)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string title = 1;</code>
     */
    String getTitle();
    /**
     * <code>string title = 1;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>bool sellWell = 2;</code>
     */
    boolean getSellWell();
  }
  /**
   * Protobuf type {@code google.protobuf.Article}
   */
  public  static final class Article extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:google.protobuf.Article)
      ArticleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Article.newBuilder() to construct.
    private Article(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Article() {
      title_ = "";
      sellWell_ = false;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Article(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 16: {

              sellWell_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoBuf.internal_static_google_protobuf_Article_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoBuf.internal_static_google_protobuf_Article_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoBuf.Article.class, ProtoBuf.Article.Builder.class);
    }

    public static final int TITLE_FIELD_NUMBER = 1;
    private volatile Object title_;
    /**
     * <code>string title = 1;</code>
     */
    public String getTitle() {
      Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SELLWELL_FIELD_NUMBER = 2;
    private boolean sellWell_;
    /**
     * <code>bool sellWell = 2;</code>
     */
    public boolean getSellWell() {
      return sellWell_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, title_);
      }
      if (sellWell_ != false) {
        output.writeBool(2, sellWell_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, title_);
      }
      if (sellWell_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, sellWell_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoBuf.Article)) {
        return super.equals(obj);
      }
      ProtoBuf.Article other = (ProtoBuf.Article) obj;

      boolean result = true;
      result = result && getTitle()
          .equals(other.getTitle());
      result = result && (getSellWell()
          == other.getSellWell());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + SELLWELL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSellWell());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoBuf.Article parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoBuf.Article parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoBuf.Article parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoBuf.Article parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoBuf.Article parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoBuf.Article parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoBuf.Article parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoBuf.Article parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoBuf.Article parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtoBuf.Article parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoBuf.Article parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoBuf.Article parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoBuf.Article prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code google.protobuf.Article}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:google.protobuf.Article)
        ProtoBuf.ArticleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoBuf.internal_static_google_protobuf_Article_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoBuf.internal_static_google_protobuf_Article_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoBuf.Article.class, ProtoBuf.Article.Builder.class);
      }

      // Construct using org.xavier.domain.protobufObj.ProtoBuf.Article.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        title_ = "";

        sellWell_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoBuf.internal_static_google_protobuf_Article_descriptor;
      }

      public ProtoBuf.Article getDefaultInstanceForType() {
        return ProtoBuf.Article.getDefaultInstance();
      }

      public ProtoBuf.Article build() {
        ProtoBuf.Article result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoBuf.Article buildPartial() {
        ProtoBuf.Article result = new ProtoBuf.Article(this);
        result.title_ = title_;
        result.sellWell_ = sellWell_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoBuf.Article) {
          return mergeFrom((ProtoBuf.Article)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoBuf.Article other) {
        if (other == ProtoBuf.Article.getDefaultInstance()) return this;
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (other.getSellWell() != false) {
          setSellWell(other.getSellWell());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoBuf.Article parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoBuf.Article) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object title_ = "";
      /**
       * <code>string title = 1;</code>
       */
      public String getTitle() {
        Object ref = title_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string title = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 1;</code>
       */
      public Builder setTitle(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 1;</code>
       */
      public Builder clearTitle() {

        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 1;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        title_ = value;
        onChanged();
        return this;
      }

      private boolean sellWell_ ;
      /**
       * <code>bool sellWell = 2;</code>
       */
      public boolean getSellWell() {
        return sellWell_;
      }
      /**
       * <code>bool sellWell = 2;</code>
       */
      public Builder setSellWell(boolean value) {

        sellWell_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool sellWell = 2;</code>
       */
      public Builder clearSellWell() {

        sellWell_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:google.protobuf.Article)
    }

    // @@protoc_insertion_point(class_scope:google.protobuf.Article)
    private static final ProtoBuf.Article DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoBuf.Article();
    }

    public static ProtoBuf.Article getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Article>
        PARSER = new com.google.protobuf.AbstractParser<Article>() {
      public Article parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Article(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Article> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Article> getParserForType() {
      return PARSER;
    }

    public ProtoBuf.Article getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_User_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_Article_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_Article_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n/core/src/main/java/google/protobuf/xav" +
      "ier.proto\022\017google.protobuf\"A\n\004User\022\r\n\005uN" +
      "ame\030\001 \001(\t\022*\n\010articles\030\002 \003(\0132\030.google.pro" +
      "tobuf.Article\"*\n\007Article\022\r\n\005title\030\001 \001(\t\022" +
      "\020\n\010sellWell\030\002 \001(\010B\'\n\035org.xavier.domain.p" +
      "rotobufObjB\006Xavierb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_google_protobuf_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_protobuf_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_User_descriptor,
        new String[] { "UName", "Articles", });
    internal_static_google_protobuf_Article_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_protobuf_Article_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_Article_descriptor,
        new String[] { "Title", "SellWell", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
